Controllers/PurchaseController.cs
using DatabaseLayer;
using LibraryManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LibraryManagementSystem.Controllers
{
    public class PurchaseController : Controller
    {
        private OnlineLibraryMgtSystemDbEntities db = new OnlineLibraryMgtSystemDbEntities();

        public ActionResult NewPurchase()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserID"])))
            {
                return RedirectToAction("Login", "Home");
            }
            double total = 0;
            var tempPur = db.PurTemDetailsTables.ToList();
            foreach(var item in tempPur)
            {
                total += (item.Qty * item.UnitPrice);
            }
            ViewBag.TotalAmount = total;
            return View(tempPur);
        }

        [HttpPost]
        public ActionResult AddItem(int BID, int Qty, int Price)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserID"])))
            {
                return RedirectToAction("Login", "Home");
            }
            int userid = Convert.ToInt32(Convert.ToString(Session["UserID"]));
            var find = db.PurTemDetailsTables.Where(i => i.BookID == BID).FirstOrDefault();
            if (find == null)
            {
                if (BID > 0 && Qty > 0 && Price > 0)
                {
                    var newItem = new PurTemDetailsTable()
                    {
                        BookID = BID,
                        Qty = Qty,
                        UnitPrice = Price
                    };
                    db.PurTemDetailsTables.Add(newItem);
                    db.SaveChanges();
                    ViewBag.Message = "Book Add Successs";
                }
            }
            else
            {
                ViewBag.Message = "Already Exist! Plz Check";
            }
            return RedirectToAction("NewPurchase");
        }

        public ActionResult DeleteConfirm(int id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserID"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var book = db.PurTemDetailsTables.Find(id);
            if (book != null)
            {
                db.Entry(book).State = System.Data.Entity.EntityState.Deleted;
                db.SaveChanges();
                ViewBag.Message = "Delete Success";
                return RedirectToAction("NewPurchase");
            }
            ViewBag.Message = "Some Unexptected issue is occure, please contact to concern person!";
            return RedirectToAction("NewPurchase");
        }

        [HttpGet]
        public ActionResult GetBooks()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserID"])))
            {
                return RedirectToAction("Login", "Home");
            }
            List<BookMV> list = new List<BookMV>();
            var bookLst = db.BookTables.ToList();
            foreach (var item in bookLst)
            {
                list.Add(new BookMV { BookName = item.BookName, BookID = item.BookID });
            }

            return Json(new { data = list }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CancelPurchase()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserID"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var list = db.PurTemDetailsTables.ToList();
            bool cancelStatus = false;
            foreach (var item in list)
            {
                db.Entry(item).State = System.Data.Entity.EntityState.Deleted;
                int noOfRecord = db.SaveChanges();
                if (cancelStatus == false)
                {
                    if (noOfRecord > 0)
                    {
                        cancelStatus = true;
                    }
                }
            }
            if (cancelStatus == true)
            {
                ViewBag.Message = "Purchase is Canceled";
                return RedirectToAction("NewPurchase");
            }
            ViewBag.Message = "Some Unexptected issue is occure, please contact to concern person!";
            return RedirectToAction("NewPurchase");
        }

        public ActionResult SelectSupplier()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserID"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var purchaseLst = db.PurTemDetailsTables.ToList();
            if (purchaseLst.Count == 0)
            {
                ViewBag.Message = "Purchase cart empty";
                return RedirectToAction("NewPurchase");
            }
            var suppliers = db.SupplierTables.ToList();
            return View(suppliers);
        }

        [HttpPost]
        public ActionResult PurchaseConfirm(FormCollection collection)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserID"])))
            {
                return RedirectToAction("Login", "Home");
            }
            int userid = Convert.ToInt32(Convert.ToString(Session["UserID"]));
            int supplierId = 0;
            string[] keys = collection.AllKeys;
            foreach (var name in keys)
            {
                if (name.Contains("name"))
                {
                    string idName = name;
                    string[] valIds = idName.Split(' ');
                    supplierId = Convert.ToInt32(valIds[1]);
                }
            }
            var purchaseTemps = db.PurTemDetailsTables.ToList();
            double total = 0;
            foreach (var item in purchaseTemps)
            {
                total += (item.Qty * item.UnitPrice);
            }
            if (total == 0)
            {
                ViewBag.Message = "Purchase cart empty";
                return View("NewPurchase");
            }

            var purchaseHeader = new PurchaseTable();
            purchaseHeader.SupplierID = supplierId;
            purchaseHeader.PurchaseDate = DateTime.Now;
            purchaseHeader.PurchaseAmount = total;
            purchaseHeader.UserID = userid;
            db.PurchaseTables.Add(purchaseHeader);
            db.SaveChanges();

            foreach (var item in purchaseTemps)
            {
                var itemPurchase = new PurchaseDetailTable()
                {
                    BookID = item.BookID,
                    PurchaseID = purchaseHeader.PurchaseID,
                    Qty = item.Qty,
                    UnitPrice = item.UnitPrice
                };
                db.PurchaseDetailTables.Add(itemPurchase);
                db.SaveChanges();

                var updateBookStock = db.BookTables.Find(item.BookID);
                updateBookStock.TotalCopies = updateBookStock.TotalCopies + item.Qty;
                updateBookStock.Price = item.UnitPrice;
                db.Entry(updateBookStock).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            db.PurTemDetailsTables.ToList().ForEach(el => {
                db.Entry(el).State = System.Data.Entity.EntityState.Deleted;
            });
            db.SaveChanges();
            ViewBag.Message = "Purchase Confirm success";
            return RedirectToAction("AllPurchase");
        }

        public ActionResult AllPurchase()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserID"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var lst = db.PurchaseTables.ToList();
            
            return View(lst);
        }

        public ActionResult PurchaseDetailsView(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserID"])))
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var purchaseDatail = db.PurchaseDetailTables.Where(item => item.PurchaseID == id);
            if (purchaseDatail == null)
            {
                return HttpNotFound();
            }
            return View(purchaseDatail);
        }
    }
}

Views/Purchase/AllPurchase.cshtml
@model IEnumerable<DatabaseLayer.PurchaseTable>

@{
    ViewBag.Title = "All Purchase";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">All Purchase</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Supplier
                        </th>
                        <th>
                            Purchase Date
                        </th>
                        <th>
                            Purchase Amount
                        </th>
                        <th>
                            User
                        </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.SupplierTable.SupplierName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PurchaseDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PurchaseAmount)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserTable.UserName)
                            </td>
                            <td>
                                @Html.ActionLink("Details", "PurchaseDetailsView", new { id = item.PurchaseID }, new { @class = "btn btn-info" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Views/Purchase/NewPurchase.cshtml
@model IEnumerable<DatabaseLayer.PurTemDetailsTable>

@{
    ViewBag.Title = "New Purchase";
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
@using (Html.BeginForm("AddItem", "Purchase", FormMethod.Post, null))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Book Details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label col-md-2">Select Book</label>
            <div class="col-md-6">
                <select class="form-control" id="BID" name="BID" required></select>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Quantity</label>
            <div class="col-md-6">
                <input type="number" class="form-control" id="Qty" name="Qty" placeholder="Enter Quantity" required />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Unit Price</label>
            <div class="col-md-6">
                <input type="number" class="form-control" id="Price" step=".01" name="Price" placeholder="Enter Unit Price" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-success" value="Add Item" />
            </div>
        </div>
    </div>
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Purchase Item List</h6>
        <h3 class="text-danger">@ViewBag.Message</h3>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Book
                        </th>
                        <th>
                            Purchase Qty
                        </th>
                        <th>
                            Unit Price
                        </th>
                        <th>
                            Item Cost
                        </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.BookTable.BookName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Qty)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UnitPrice)
                            </td>
                            <td>
                                @(string.Format("{0:0.000}", Math.Truncate(item.Qty * item.UnitPrice * 10)/10))
                            </td>
                            <td>
                                @Html.ActionLink("Delete", "DeleteConfirm", new { id = item.PurTemID }, new { @class = "btn btn-danger" })
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td></td>
                        <td></td>
                        <td style="background-color: black; color: white">Total Amount</td>
                        <td style="background-color: black; color: white">
                            @(string.Format("{0:0.000}", Math.Truncate(ViewBag.TotalAmount * 10)/10)) VND
                        </td>
                        <td></td>
                    </tr>
                </tfoot>
            </table>
            <div style="margin-top: 20px; float:right">
                @Html.ActionLink("Next", "SelectSupplier", null, new { @class = "btn btn-success", style = "padding:20px" })
                @Html.ActionLink("Cancel", "CancelPurchase", null, new { @class = "btn btn-danger", style = "padding:20px" })
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $.ajax({
            url: '@Url.Action("GetBooks", "Purchase")',
            type: 'GET',
            data: '{}',
            success: function (res) {
                console.log("aaaaa: ", res.data);
                for (var i = 0; i < res.data.length; i++) {
                    $('#BID').append("<option value=" + res.data[i].BookID + ">" + res.data[i].BookName + "</option>");
                }
            },
            error: function () {

            }
        });
    });
</script>

Views/Purchase/PurchaseDetailsView.cshtml
@model IEnumerable<DatabaseLayer.PurchaseDetailTable>

@{
    ViewBag.Title = "Purchase Details";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Purchase cart</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.BookTable.BookTitle)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Qty)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.UnitPrice)
                        </th>
                        <th>Book Cost</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.BookTable.BookTitle)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Qty)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UnitPrice)
                            </td>
                            <td>
                                @(string.Format("{0:0.000}", Math.Truncate(item.Qty * item.UnitPrice * 10)/10))
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>

Views/Purchase/SelectSupplier.cshtml
@model IEnumerable<DatabaseLayer.SupplierTable>

@{
    ViewBag.Title = "SelectSupplier";
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
@using (Html.BeginForm("PurchaseConfirm", "Purchase", FormMethod.Post, null))
{
    <div class="card">
        <div class="card card-flat">
            <div class="card-header">
                <input type="submit" style="float:right" class="btn btn-success" value="Finilize Purchase" />
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-hover" id="dataTable">
                        <thead style="background-color: lightgray">
                            <tr>
                                <th>Supplier</th>
                                <th>Contact No</th>
                                <th>Suplier Email</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.SupplierName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ContactNo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Email)
                                    </td>
                                    <td>
                                        <input type="checkbox" name="name @item.SupplierID" class="chb" />
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        $(".chb").change(function (event) {
            $(".chb").prop('checked', false);
            $(this).prop('checked', true);
        });
    });
</script>